#!/bin/bash

set -eu
set -o pipefail

cat << "EOF1" > /etc/yum.repos.d/centos7-latest.repo
[rhel7]
name=centos7
baseurl=http://mirror.switch.ch/ftp/mirror/centos/7/os/x86_64/
enabled=1
metadata_expire=7d
gpgcheck=0
EOF1

yum -y install epel-release

