#!/bin/bash
cat <<- "EOF1" > /etc/cloud/cloud.cfg.d/99-local-mirror-only.cfg
apt_preserve_sources_list: true
EOF1

cat  <<- EOF2 >> /etc/apt/sources.list
deb http://ftp.ch.debian.org/debian-security/ /updates main contrib non-free
deb http://security.debian.org/ /updates main contrib non-free
EOF2

sed -i 's/nova.clouds.archive.debian.com/ch.archive.debian.com/g' /etc/apt/sources.list

